 print("Hello, World!")
print("This is my first Python program.")
print("I'm excited to learn Python programming!")
print("Let's get started!")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")
print("shivani soni")

